# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    docker run -p 4040:4040 -p 5050:5050 -e CHECK_RESULTS_EVERY_SECONDS=3 -e KEEP_HISTORY="TRUE" -v ${PWD}/output:/app/allure-results frankescobar/allure-docker-service
    npm install
    npm test
  displayName: 'Run tests'
- task: AllureGenerate@1
  inputs:
    resultsDir: 'output'
    targetDir: 'output'
